plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()

    exclusiveContent {
        forRepository {
            maven {
                name = 'RyanHCode Maven'
                url = 'https://maven.ryanhcode.dev/releases'
            }
        }
        filter {
            includeGroup('dev.ryanhcode.sable') // Sable
            includeGroup('dev.ryanhcode.sable-companion') // Sable Companion
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Fuzs Maven'
                url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven'
            }
        }
        filter {
            includeGroup('fuzs.forgeconfigapiport') // Forge Config API Port (Sable dependency)
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'BlameJared Maven'
                url = 'https://maven.blamejared.com'
            }
        }
        filter {
            includeGroup('vazkii.patchouli') // Patchouli
            includeGroup('foundry.veil') // Veil (Sable dependency)
            includeGroup('io.github.ocelot') // GLSL Processor (Veil dependency)
            includeGroup('gg.moonflower') // Molang Compiler (Veil dependency)
        }
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth Maven'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup('maven.modrinth') // Psi...
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation("dev.ryanhcode.sable:sable-neoforge-${project.minecraft_version}:${project.sable_version}") {
        exclude group: 'com.simibubi.create'
        exclude group: 'net.createmod.ponder'
        exclude group: 'dev.engine-room.flywheel'
        exclude group: 'com.tterrag.registrate'
    }
    implementation("maven.modrinth:psi:${project.psi_version}")
    implementation("vazkii.patchouli:Patchouli:${project.patchouli_version}")
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
